### ISSUE TITLE
Windows Building not correctly cacching

### ISSUE THREAD

**Issue by ConnorY97** [AlexMollard/SlimeOdyssey#37]
```
Run actions/cache@v4
  with:
    path: ~/.cpm
    key: Windows-cpm-e6f2d4b87142345682f56164fb820c9f32059b7885e7193f78980ce2fee53bdd
    restore-keys: Windows-cpm-
  
    enableCrossOsArchive: false
    fail-on-cache-miss: false
    lookup-only: false
    save-always: false
Cache not found for input keys: Windows-cpm-e6f2d4b87142345682f56164fb820c9f32059b7885e7193f78980ce2fee53bdd, Windows-cpm-
```

Need to investigate why caches are not being found.
